import type { Service, Project, Testimonial, ProcessStep, Stat, NavLink } from "@/types";

export const NAV_LINKS: NavLink[] = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Services", href: "/services" },
  { label: "Projects", href: "/projects" },
  { label: "Process", href: "/process" },
  { label: "Testimonials", href: "/testimonials" },
  { label: "Contact", href: "/contact" },
];

export const STATS: Stat[] = [
  { label: "Years of Experience", value: 18, suffix: "+", icon: "Award" },
  { label: "Projects Completed", value: 500, suffix: "+", icon: "Building2" },
  { label: "Happy Clients", value: 400, suffix: "+", icon: "Users" },
  { label: "Business Divisions", value: 5, suffix: "", icon: "Layers" },
];

export const SERVICES: Service[] = [
  {
    id: "construction",
    title: "Construction",
    description: "End-to-end building construction — residential, commercial, and industrial projects delivered with precision engineering and premium materials.",
    icon: "Building2",
    image: "https://images.unsplash.com/photo-1590859808308-3d2d9c515b1a?w=600&q=80",
    features: ["Residential & commercial buildings", "Structural engineering", "Turnkey project delivery", "On-time, on-budget guarantee"],
    href: "/services#construction",
  },
  {
    id: "petroleum",
    title: "Petroleum & Petrol Pump",
    description: "Complete petrol pump setup, fuel station construction, and petroleum infrastructure — from site planning to operational handover.",
    icon: "Fuel",
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600&q=80",
    features: ["Fuel station design & build", "Underground tank installation", "Canopy & forecourt construction", "Safety & compliance certification"],
    href: "/services#petroleum",
  },
  {
    id: "concrete-blocks",
    title: "Concrete Blocks",
    description: "High-quality concrete block manufacturing and supply for construction projects of all scales — consistent strength, precise dimensions.",
    icon: "Boxes",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80",
    features: ["Standard & custom block sizes", "High-compression strength", "Bulk supply & delivery", "Quality certified products"],
    href: "/services#concrete-blocks",
  },
  {
    id: "ready-mix",
    title: "Ready Mix Concrete",
    description: "Factory-mixed, site-delivered concrete in the exact grade you need — guaranteed consistency, zero wastage, and fast turnaround.",
    icon: "Layers",
    image: "/images/ready-mix.jpg",
    features: ["M10 to M50 grade concrete", "Transit mixer delivery", "On-site testing & reports", "Large-volume contracts"],
    href: "/services#ready-mix",
  },
  {
    id: "transport",
    title: "Transport",
    description: "Reliable heavy-material transport solutions for construction sites — on-time delivery of aggregates, concrete, equipment, and supplies.",
    icon: "Truck",
    image: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=600&q=80",
    features: ["Heavy-load haulage", "Construction material logistics", "Fleet of tippers & trailers", "City & inter-city routes"],
    href: "/services#transport",
  },
];

export const PROJECTS: Project[] = [
  {
    id: "commercial-complex",
    title: "Skyline Commercial Complex",
    location: "Bangalore, KA",
    year: 2024,
    category: "Construction",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80",
    description: "8-storey commercial complex with 120,000 sq ft of office and retail space, completed 2 weeks ahead of schedule.",
    area: "1,20,000 sq ft",
    duration: "22 months",
  },
  {
    id: "petrol-pump-highway",
    title: "Highway Fuel Station",
    location: "Bangalore, KA",
    year: 2024,
    category: "Petroleum",
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&q=80",
    description: "Full-service petrol pump with canopy, underground tanks, convenience store, and EV charging bays on a high-traffic expressway.",
    area: "12,000 sq ft",
    duration: "8 months",
  },
  {
    id: "residential-township",
    title: "Green Valley Township",
    location: "Bangalore, KA",
    year: 2024,
    category: "Construction",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    description: "240-unit residential township supplying over 15,000 m³ of ready mix concrete and 8 lakh concrete blocks from our own plants.",
    area: "4,80,000 sq ft",
    duration: "30 months",
  },
  {
    id: "rmc-supply-bridge",
    title: "River Bridge RMC Supply",
    location: "Bangalore, KA",
    year: 2023,
    category: "Ready Mix",
    image: "/images/ready-mix.jpg",
    description: "Supplied over 22,000 m³ of M40-grade ready mix concrete for a 1.2 km river bridge project under a government infrastructure contract.",
    area: "N/A",
    duration: "14 months",
  },
  {
    id: "transport-fleet-project",
    title: "Industrial Zone Logistics",
    location: "Bangalore, KA",
    year: 2023,
    category: "Transport",
    image: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&q=80",
    description: "Dedicated fleet of 30 tippers providing daily material transport across an industrial manufacturing zone, handling 500+ tonnes/day.",
    area: "N/A",
    duration: "Ongoing",
  },
  {
    id: "block-supply-airport",
    title: "Airport Terminal Block Supply",
    location: "Bangalore, KA",
    year: 2022,
    category: "Concrete Blocks",
    image: "https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800&q=80",
    description: "Supplied 12 lakh precision-cast concrete blocks for a new airport terminal perimeter wall and internal partitioning systems.",
    area: "N/A",
    duration: "10 months",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "t1",
    name: "Rajesh & Priya Mehta",
    role: "Residential Clients",
    avatar: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=100&q=80",
    review: "Khushi Construction built our dream home exactly as planned — on time and within budget. Their team's attention to detail and use of premium materials gave us total confidence throughout the project.",
    rating: 5,
    project: "Green Valley Township",
  },
  {
    id: "t2",
    name: "Sunil Patil",
    role: "Petroleum Station Owner",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80",
    review: "From site survey to opening day, Khushi handled our petrol pump project flawlessly. Safety compliance was top-notch and we were operational ahead of schedule. Highly professional team.",
    rating: 5,
    project: "Highway Fuel Station",
  },
  {
    id: "t3",
    name: "Amit Sharma",
    role: "Civil Contractor",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    review: "We rely on Khushi's ready mix concrete for all our major projects. Consistent grade, on-time delivery, and proper test reports every time. They are our first call for any concrete requirement.",
    rating: 5,
    project: "River Bridge RMC Supply",
  },
  {
    id: "t4",
    name: "Vikram Desai",
    role: "Real Estate Developer",
    avatar: "https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=100&q=80",
    review: "The concrete blocks from Khushi are consistently strong and dimensionally accurate. Using their blocks and transport together saved us both cost and coordination headaches on our township project.",
    rating: 5,
    project: "Airport Terminal Block Supply",
  },
  {
    id: "t5",
    name: "Ganesh Kulkarni",
    role: "Logistics Manager, MIDC",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
    review: "Khushi's transport division is extremely reliable. Their fleet runs on schedule even in peak season. We moved over 500 tonnes a day for months without a single delay. Truly dependable partners.",
    rating: 5,
    project: "Industrial Zone Logistics",
  },
];

export const PROCESS_STEPS: ProcessStep[] = [
  { id: 1, title: "Initial Consultation", description: "We meet to understand your requirements across construction, materials, or logistics — and assess your site, scope, and timeline.", icon: "MessageSquare", duration: "1-2 days" },
  { id: 2, title: "Design & Planning", description: "Our engineers and planners develop detailed drawings, material schedules, and logistics plans tailored to your project.", icon: "PenTool", duration: "2-4 weeks" },
  { id: 3, title: "Budget Estimation", description: "Transparent, itemized quotation covering construction, concrete supply, block supply, or transport — no hidden costs.", icon: "Calculator", duration: "1 week" },
  { id: 4, title: "Foundation & Groundwork", description: "Expert excavation, foundation laying, and concrete work using our own ready mix concrete for assured quality.", icon: "Layers", duration: "3-6 weeks" },
  { id: 5, title: "Structural Construction", description: "Steel or concrete framing, block masonry using our own concrete blocks, and full structural assembly.", icon: "Building2", duration: "6-12 weeks" },
  { id: 6, title: "MEP & Finishing", description: "Mechanical, electrical, and plumbing systems installed, followed by interior finishing and site cleanup.", icon: "Zap", duration: "6-12 weeks" },
  { id: 7, title: "Material & Transport Logistics", description: "All construction materials — concrete, blocks, aggregates — transported by our own fleet, ensuring no third-party delays.", icon: "Truck", duration: "Ongoing" },
  { id: 8, title: "Final Inspection", description: "Comprehensive walkthrough, compliance checks, and punch list completion before handover.", icon: "ClipboardCheck", duration: "1-2 weeks" },
  { id: 9, title: "Handover & Support", description: "Delivery with full documentation, warranties, and post-completion support across all our service divisions.", icon: "Key", duration: "1 day" },
];
