import type { Service, Project, Testimonial, ProcessStep, Stat, NavLink } from "@/types";

export const NAV_LINKS: NavLink[] = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Services", href: "/services" },
  { label: "Projects", href: "/projects" },
  { label: "Process", href: "/process" },
  { label: "Testimonials", href: "/testimonials" },
  { label: "Contact", href: "/contact" },
];

export const STATS: Stat[] = [
  { label: "Years of Experience", value: 18, suffix: "+", icon: "Award" },
  { label: "Projects Completed", value: 500, suffix: "+", icon: "Building2" },
  { label: "Happy Clients", value: 400, suffix: "+", icon: "Users" },
  { label: "Business Divisions", value: 5, suffix: "", icon: "Layers" },
];

export const SERVICES: Service[] = [
  {
    id: "construction",
    title: "Construction",
    description:
      "End-to-end building construction for residential, commercial, and industrial projects, handled by our in-house engineering, site management, and quality teams from excavation to final handover.",
    bestFor:
      "Villa projects, apartment blocks, office buildings, and multi-phase industrial developments.",
    deliveryWindow: "Typical project cycle: 8 to 24 months based on scope and approvals.",
    monthlyCapacity: "Active management capacity: 12+ concurrent sites with milestone tracking.",
    icon: "Building2",
    image: "https://images.unsplash.com/photo-1590859808308-3d2d9c515b1a?w=600&q=80",
    features: [
      "Residential and commercial construction execution",
      "Structural design coordination and RCC planning",
      "MEP integration with staged quality checks",
      "Interior and external finishing support",
      "Procurement, labor, and vendor management",
      "Weekly progress reporting with milestone reviews",
      "On-time, on-budget delivery discipline",
    ],
    href: "/services#construction",
    steps: [
      { number: 1, title: "Site Assessment & Documentation", description: "Evaluate site conditions, obtain regulatory approvals, and finalize design and material specifications." },
      { number: 2, title: "Excavation & Foundation", description: "Clear site, conduct excavation, and construct foundations using our quality-controlled concrete." },
      { number: 3, title: "Structural Framework", description: "Erect RCC or steel structure with staged quality inspections and material testing at each milestone." },
      { number: 4, title: "MEP Installation", description: "Route and install mechanical, electrical, and plumbing systems with compliance verification." },
      { number: 5, title: "Interior & Exterior Finishing", description: "Complete interior finishes, external facade, and landscaping with premium materials and craftsmanship." },
      { number: 6, title: "Final Inspection & Handover", description: "Comprehensive walkthrough, compliance certification, and project handover with full documentation." },
    ],
  },
  {
    id: "petroleum",
    title: "Petroleum & Petrol Pump",
    description:
      "Complete petrol pump setup and petroleum infrastructure delivery, including civil construction, underground systems, forecourt works, utility coordination, and commissioning support.",
    bestFor:
      "Highway fuel stations, city refueling outlets, fleet depots, and retail fuel expansion projects.",
    deliveryWindow: "Average completion: 5 to 9 months including statutory coordination.",
    monthlyCapacity: "Parallel execution support for multiple station development programs.",
    icon: "Fuel",
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600&q=80",
    features: [
      "Fuel station design and layout implementation",
      "Underground tank pit, piping, and chamber work",
      "Canopy, driveway, and forecourt civil execution",
      "Drainage, electrical trenching, and utility routing",
      "Retail block and office room construction",
      "Safety-first execution aligned with compliance standards",
      "Commissioning support through handover stage",
    ],
    href: "/services#petroleum",
    steps: [
      { number: 1, title: "Regulatory Approval & Planning", description: "Coordinate with petroleum authorities and local authorities to obtain necessary permits and finalize design layout." },
      { number: 2, title: "Civil Site Preparation", description: "Excavate tank pit, prepare ground levels, and construct underground chamber structures with safety standards." },
      { number: 3, title: "Underground Infrastructure", description: "Install underground tanks, piping systems, and ancillary chambers with leak detection and safety systems." },
      { number: 4, title: "Canopy & Forecourt", description: "Construct fuel dispenser canopy, driveway, and forecourt using our concrete and blocks for durability." },
      { number: 5, title: "Retail & Utility Installation", description: "Build retail block, office areas, and install electrical, drainage, and utility systems." },
      { number: 6, title: "Commissioning & Handover", description: "Conduct safety inspections, system testing, and obtain operational clearance before handover." },
    ],
  },
  {
    id: "concrete-blocks",
    title: "Concrete Blocks",
    description:
      "High-strength concrete block manufacturing and supply for projects that demand dimensional consistency, dependable compressive strength, and uninterrupted material availability.",
    bestFor:
      "Boundary walls, load and non-load partitions, mass housing, and institutional building programs.",
    deliveryWindow: "Dispatch windows from same-day to 72 hours based on quantity and location.",
    monthlyCapacity: "Large-volume production lines for continuous bulk supply contracts.",
    icon: "Boxes",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80",
    features: [
      "Standard and custom block dimensions",
      "Controlled curing for stable product quality",
      "High-compression mix design options",
      "Batch-level quality checks before dispatch",
      "Palletized handling to reduce breakage",
      "Bulk supply planning for phased construction",
      "On-time delivery through our transport network",
    ],
    href: "/services#concrete-blocks",
    steps: [
      { number: 1, title: "Project Requirement Assessment", description: "Evaluate your project specifications — block dimensions, strength requirements, and delivery schedule." },
      { number: 2, title: "Mix Design & Production Setup", description: "Prepare optimized concrete mix using quality materials and set up automated production lines." },
      { number: 3, title: "Block Manufacturing", description: "Produce blocks using precision molds ensuring uniform dimensions and consistent compressive strength." },
      { number: 4, title: "Quality Testing", description: "Conduct compression tests and dimensional checks on every batch before approval." },
      { number: 5, title: "Curing & Conditioning", description: "Controlled curing process to achieve optimal strength and product stability before dispatch." },
      { number: 6, title: "Palletization & Delivery", description: "Palletize blocks with precision handling and deliver via our transport fleet with minimal breakage." },
    ],
  },
  {
    id: "ready-mix",
    title: "Ready Mix Concrete",
    description:
      "Plant-batched, quality-controlled ready mix concrete supplied in required grades with coordinated dispatch planning, on-site delivery, and traceable quality documentation.",
    bestFor:
      "Residential slabs, commercial structures, foundations, roads, and infrastructure packages.",
    deliveryWindow: "Slot-based dispatch with fast turnaround for urgent pours.",
    monthlyCapacity: "High-volume daily production with multi-mixer route allocation.",
    icon: "Layers",
    image: "/images/ready-mix.jpg",
    features: [
      "Concrete grades from M10 to M50",
      "Transit mixer and pump-coordinated delivery",
      "Moisture and batching control at plant",
      "On-site slump test and quality records",
      "Scheduled pours for large slab and raft works",
      "Supply continuity for long-duration projects",
      "Technical support for mix selection and application",
    ],
    href: "/services#ready-mix",
    steps: [
      { number: 1, title: "Order Placement & Scheduling", description: "Provide your concrete grade requirement and schedule a pour slot through our dispatch coordination team." },
      { number: 2, title: "Mix Design Confirmation", description: "Our engineers confirm the optimal concrete grade (M10–M50) based on your structural requirements." },
      { number: 3, title: "Batch Preparation at Plant", description: "Accurately batch aggregates, cement, and water using automated weighing systems with moisture control." },
      { number: 4, title: "Transit Mixer Loading", description: "Load concrete into transit mixers with controlled agitation to maintain uniformity during transport." },
      { number: 5, title: "On-Site Delivery & Testing", description: "Deliver concrete to your site and perform slump and consistency tests before pour commencement." },
      { number: 6, title: "Pour Support & Documentation", description: "Provide on-site technical support and deliver complete test certificates and quality documentation." },
    ],
  },
  {
    id: "transport",
    title: "Transport",
    description:
      "Reliable heavy-material transport for construction and industrial operations, with route planning, fleet coordination, and dispatch monitoring to keep projects moving without delays.",
    bestFor:
      "Aggregate movement, construction material shuttling, plant-to-site supply, and heavy equipment logistics.",
    deliveryWindow: "Daily, shift-based, and project-specific dispatch models available.",
    monthlyCapacity: "Fleet support for high-frequency loads across city and inter-city routes.",
    icon: "Truck",
    image: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=600&q=80",
    features: [
      "Heavy-load haulage for bulk construction materials",
      "Tipper and trailer fleet deployment",
      "Planned route and dispatch scheduling",
      "Aggregate, sand, and block movement support",
      "Plant-to-site and multi-site load balancing",
      "City and inter-city operational coverage",
      "Time-bound delivery tracking and escalation response",
    ],
    href: "/services#transport",
    steps: [
      { number: 1, title: "Load Requirement Assessment", description: "Specify material type, quantity, source location, and destination for optimized fleet allocation." },
      { number: 2, title: "Route Planning & Scheduling", description: "Our logistics team plans efficient routes considering traffic, site access restrictions, and delivery windows." },
      { number: 3, title: "Fleet Dispatch", description: "Deploy appropriate vehicles (tippers, trailers) from our fleet based on load type and volume." },
      { number: 4, title: "Material Loading", description: "Safely load materials with precision to ensure balance, prevent spillage, and meet weight limits." },
      { number: 5, title: "In-Transit Monitoring", description: "Track vehicle location in real-time and maintain communication for schedule adherence and issue resolution." },
      { number: 6, title: "On-Site Unloading & Documentation", description: "Professional unloading at destination with delivery receipts, weight tickets, and quality verification." },
    ],
  },
];

export const PROJECTS: Project[] = [
  {
    id: "commercial-complex",
    title: "Skyline Commercial Complex",
    location: "Bangalore, KA",
    year: 2024,
    category: "Construction",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80",
    description: "8-storey commercial complex with 120,000 sq ft of office and retail space, completed 2 weeks ahead of schedule.",
    area: "1,20,000 sq ft",
    duration: "22 months",
  },
  {
    id: "petrol-pump-highway",
    title: "Highway Fuel Station",
    location: "Bangalore, KA",
    year: 2024,
    category: "Petroleum",
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&q=80",
    description: "Full-service petrol pump with canopy, underground tanks, convenience store, and EV charging bays on a high-traffic expressway.",
    area: "12,000 sq ft",
    duration: "8 months",
  },
  {
    id: "residential-township",
    title: "Green Valley Township",
    location: "Bangalore, KA",
    year: 2024,
    category: "Construction",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    description: "240-unit residential township supplying over 15,000 m³ of ready mix concrete and 8 lakh concrete blocks from our own plants.",
    area: "4,80,000 sq ft",
    duration: "30 months",
  },
  {
    id: "rmc-supply-bridge",
    title: "River Bridge RMC Supply",
    location: "Bangalore, KA",
    year: 2023,
    category: "Ready Mix",
    image: "/images/ready-mix.jpg",
    description: "Supplied over 22,000 m³ of M40-grade ready mix concrete for a 1.2 km river bridge project under a government infrastructure contract.",
    area: "N/A",
    duration: "14 months",
  },
  {
    id: "transport-fleet-project",
    title: "Industrial Zone Logistics",
    location: "Bangalore, KA",
    year: 2023,
    category: "Transport",
    image: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&q=80",
    description: "Dedicated fleet of 30 tippers providing daily material transport across an industrial manufacturing zone, handling 500+ tonnes/day.",
    area: "N/A",
    duration: "Ongoing",
  },
  {
    id: "block-supply-airport",
    title: "Airport Terminal Block Supply",
    location: "Bangalore, KA",
    year: 2022,
    category: "Concrete Blocks",
    image: "https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800&q=80",
    description: "Supplied 12 lakh precision-cast concrete blocks for a new airport terminal perimeter wall and internal partitioning systems.",
    area: "N/A",
    duration: "10 months",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "t1",
    name: "Shankar Family",
    role: "Homeowners, Jayanagar 4th Block, Bengaluru",
    review: "Our old 30x40 house in Jayanagar was rebuilt as a three-floor home with parking and rental units. The team handled BBMP paperwork, demolition, and reconstruction in phases, so we could plan our move properly.",
    rating: 5,
    project: "Custom Home Redevelopment - Jayanagar",
  },
  {
    id: "t2",
    name: "Prakash N.",
    role: "Fuel Retail Operator, Mysore Road, Bengaluru",
    review: "For our station upgrade on Mysore Road, civil work had to be coordinated around daily operations. Kushi Groups Tavarekere planned night shifts for critical pours and kept safety barriers and access routes properly managed throughout.",
    rating: 5,
    project: "Petrol Station Upgrade - Mysore Road",
  },
  {
    id: "t3",
    name: "Ravi K.",
    role: "Civil Contractor, Whitefield, Bengaluru",
    review: "We used their RMC supply for a multi-block apartment site in Whitefield. Slump consistency was reliable, and dispatch timing was coordinated with our pump schedule, which reduced waiting time on slab days.",
    rating: 5,
    project: "Apartment RMC Supply - Whitefield",
  },
  {
    id: "t4",
    name: "Farheen A.",
    role: "Developer Representative, Yelahanka, Bengaluru",
    review: "For our Yelahanka warehouse compound, we sourced both concrete blocks and transport from one vendor. The block dimensions were consistent and breakage during unloading was minimal, which helped maintain pace.",
    rating: 5,
    project: "Warehouse Block Supply - Yelahanka",
  },
  {
    id: "t5",
    name: "Naveen P.",
    role: "Site Logistics Lead, Sarjapur Road, Bengaluru",
    review: "Our Sarjapur Road site had narrow access windows for heavy vehicles. Their transport team staggered trips based on traffic and gate restrictions, so aggregate and sand supply stayed steady without site congestion.",
    rating: 5,
    project: "Construction Logistics - Sarjapur Road",
  },
];

export const PROCESS_STEPS: ProcessStep[] = [
  { id: 1, title: "Initial Consultation", description: "We meet to understand your requirements across construction, materials, or logistics — and assess your site, scope, and timeline.", icon: "MessageSquare", duration: "1-2 days" },
  { id: 2, title: "Design & Planning", description: "Our engineers and planners develop detailed drawings, material schedules, and logistics plans tailored to your project.", icon: "PenTool", duration: "2-4 weeks" },
  { id: 3, title: "Budget Estimation", description: "Transparent, itemized quotation covering construction, concrete supply, block supply, or transport — no hidden costs.", icon: "Calculator", duration: "1 week" },
  { id: 4, title: "Foundation & Groundwork", description: "Expert excavation, foundation laying, and concrete work using our own ready mix concrete for assured quality.", icon: "Layers", duration: "3-6 weeks" },
  { id: 5, title: "Structural Construction", description: "Steel or concrete framing, block masonry using our own concrete blocks, and full structural assembly.", icon: "Building2", duration: "6-12 weeks" },
  { id: 6, title: "MEP & Finishing", description: "Mechanical, electrical, and plumbing systems installed, followed by interior finishing and site cleanup.", icon: "Zap", duration: "6-12 weeks" },
  { id: 7, title: "Material & Transport Logistics", description: "All construction materials — concrete, blocks, aggregates — transported by our own fleet, ensuring no third-party delays.", icon: "Truck", duration: "Ongoing" },
  { id: 8, title: "Final Inspection", description: "Comprehensive walkthrough, compliance checks, and punch list completion before handover.", icon: "ClipboardCheck", duration: "1-2 weeks" },
  { id: 9, title: "Handover & Support", description: "Delivery with full documentation, warranties, and post-completion support across all our service divisions.", icon: "Key", duration: "1 day" },
];
